[platformio]
extra_configs = platformio.local.ini

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
extra_scripts = pre:scripts/generate_secrets_header.py

lib_deps =
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit SHT4x Library@^1.0.5
  adafruit/Adafruit BMP3XX Library@^2.1.6
  wollewald/INA226_WE@^1.2.9

[env:esp32dev]
board = esp32dev
upload_protocol = esptool
build_flags =
  -DESP32_METEO_I2C_SDA_PIN=21
  -DESP32_METEO_I2C_SCL_PIN=22
  -DESP32_METEO_HA_MODEL=ESP32_METEO_MODEL_ESP32_DEVKIT

[env:esp32dev_ota]
board = esp32dev
upload_protocol = espota
upload_port = 192.168.1.148
build_flags =
  -DESP32_METEO_I2C_SDA_PIN=21
  -DESP32_METEO_I2C_SCL_PIN=22
  -DESP32_METEO_HA_MODEL=ESP32_METEO_MODEL_ESP32_DEVKIT

[env:esp32c3]
board = esp32-c3-devkitm-1
upload_protocol = esptool
build_flags =
  -DESP32_METEO_TARGET_C3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DESP32_METEO_I2C_SDA_PIN=4
  -DESP32_METEO_I2C_SCL_PIN=5
  -DESP32_METEO_HA_MODEL=ESP32_METEO_MODEL_ESP32C3_DEVKITM1

[env:esp32c3_ota]
board = esp32-c3-devkitm-1
upload_protocol = espota
upload_port = esp32-meteo-c3.local
build_flags =
  -DESP32_METEO_TARGET_C3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DESP32_METEO_I2C_SDA_PIN=4
  -DESP32_METEO_I2C_SCL_PIN=5
  -DESP32_METEO_HA_MODEL=ESP32_METEO_MODEL_ESP32C3_DEVKITM1
